# Generated by Django 5.2.3 on 2025-07-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.CharField(max_length=150)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes"),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("phone_no", models.CharField(max_length=13)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
    ]
