# Generated by Django 5.2.3 on 2025-07-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone_no",
            field=models.CharField(max_length=14),
        ),
    ]
