# Generated by Django 5.2.3 on 2025-07-01 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("profiles", "0002_alter_employeeprofile_phone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="employees.employee"
            ),
        ),
    ]
