# Generated by Django 5.2.3 on 2025-07-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="image",
        ),
    ]
